// pages/api/notify-flag.js
import sgMail from "@sendgrid/mail";

const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
const ADMIN_EMAILS =
  (process.env.ADMIN_EMAILS ||
    "mohitkmr8566@gmail.com,warea.admin@gmail.com").split(",");

sgMail.setApiKey(SENDGRID_API_KEY);

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end();

  const { productId, reviewId, productTitle, reporter, review } = req.body || {};
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://warea.vercel.app";

  if (!SENDGRID_API_KEY) {
    console.warn("SENDGRID_API_KEY not configured.");
    return res.status(200).json({ ok: true, skipped: true });
  }

  try {
    const html = `
      <div style="font-family:Segoe UI,Arial,sans-serif;color:#333">
        <h2>🚩 Review Flagged on <span style="color:#d97706">Warea</span></h2>
        <p><b>Product:</b> ${productTitle || productId}</p>
        <p><b>Reporter:</b> ${reporter}</p>
        <p><b>Rating:</b> ${review?.rating ?? "N/A"} ⭐</p>
        <p><b>Flags:</b> ${review?.flags ?? 1}</p>
        <p><b>Comment:</b></p>
        <blockquote style="margin:8px 0;padding:10px 14px;background:#f9fafb;border-left:3px solid #d97706;">
          ${review?.comment || "(no comment)"}
        </blockquote>
        <p>
          <a href="${baseUrl}/product/${productId}" style="color:#2563eb;text-decoration:none;">🔗 View Product</a> |
          <a href="${baseUrl}/admin/reviews" style="color:#2563eb;text-decoration:none;">⚙️ Moderate Reviews</a>
        </p>
        <hr style="margin:20px 0;border:none;border-top:1px solid #ddd" />
        <small>This message was automatically generated by Warea Review Moderation System.</small>
      </div>
    `;

    await sgMail.send({
      to: ADMIN_EMAILS,
      from: process.env.SENDER_EMAIL || ADMIN_EMAILS[0],
      subject: `🚩 Review flagged – ${productTitle || productId}`,
      html,
    });

    res.status(200).json({ ok: true });
  } catch (err) {
    console.error("notify-flag error:", err);
    res.status(500).json({ error: "Email send failed" });
  }
}
